'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'ja' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  ja: {
    'nav.pricing': '料金プラン',
    'nav.docs': 'ドキュメント',
    'nav.login': 'ログイン',
    'nav.signup': '無料で始める',
    'hero.badge': 'プロフェッショナル財務データAPI',
    'hero.title1': '次世代金融データ',
    'hero.title2': 'プラットフォーム',
    'hero.description1': '日本最大級のXBRL財務データベースで、企業の財務情報を瞬時に取得。',
    'hero.description2': '投資判断に必要なデータを効率的に分析できます。',
    'hero.cta.signup': '無料トライアル開始',
    'hero.cta.login': 'ログイン',
    'hero.cta.demo': 'ライブデモ',
    'hero.stat1': '3,800+',
    'hero.stat1Label': '上場企業データ',
    'hero.stat2': '有価証券報告書データ取得',
    'hero.stat2Label': '履歴データ保有',
    'faq.title': 'よくある質問',
    'faq.description': 'XBRL Financial APIについてのよくある質問にお答えします',
    'faq.q1': 'このサービスは投資助言を提供しますか？',
    'faq.a1': 'いいえ、当サービスは投資助言業ではありません。財務データの分析ツールとして情報提供のみを行っており、具体的な投資判断や推奨は行いません。投資に関する最終的な判断は、必ずお客様ご自身の責任で行ってください。',
    'faq.q2': 'どのようなデータが取得できますか？',
    'faq.a2': '日本の上場企業の有価証券報告書から抽出した財務データ、業績指標、企業情報などを提供しています。すべてのデータは公開情報に基づいています。',
    'faq.q3': 'APIの利用制限はありますか？',
    'faq.a3': 'フリーミアムプランでは直近１年間のデータアクセス、スタンダードプランではすべてのデータアクセス利用可能です。',
    'faq.q4': 'データの正確性は保証されますか？',
    'faq.a4': '公開されている有価証券報告書に基づいてデータを提供していますが、データの正確性や完全性について保証するものではありません。重要な投資判断の際は、必ず一次情報をご確認ください。',
    'faq.q5': 'どの企業のデータが利用できますか？',
    'faq.a5': '東証プライム、スタンダード、グロース市場に上場している企業のデータを提供しています。対象企業は定期的に更新されます。',
    'faq.q6': '商用利用は可能ですか？',
    'faq.a6': 'はい、商用利用が可能です。ただし、取得したデータを第三者に販売した損害。または、AI分析結果に基づく損害について当社は一切の責任を負いかねます。',
    'footer.copyright': '© 2025 Financial Information next (FIN). All rights reserved.',
    'footer.github': 'GitHub',
    // Login page (alternative /login route)
    'login2.title': 'アカウントにログイン',
    'login2.orCreate': 'または',
    'login2.createAccount': '無料でアカウントを作成',
    'login2.email': 'メールアドレス',
    'login2.password': 'パスワード',
    'login2.emailPlaceholder': 'your@email.com',
    'login2.passwordPlaceholder': 'パスワードを入力',
    'login2.rememberMe': 'ログイン状態を保持',
    'login2.forgotPassword': 'パスワードを忘れた方',
    'login2.loginButton': 'ログイン',
    'login2.loggingIn': 'ログイン中...',
    'login2.noAccount': 'アカウントをお持ちでない方は',
    'login2.signupLink': 'こちらから無料登録',
    'login2.error.invalid': 'メールアドレスまたはパスワードが正しくありません',
    'login2.error.general': 'ログイン中にエラーが発生しました',
    // SearchDemo component
    'home.searchDemo.badge': 'インタラクティブAPI',
    'home.searchDemo.title': 'リアルタイム',
    'home.searchDemo.titleSuffix': '財務分析',
    'home.searchDemo.subtitle': '財務データに瞬時にアクセス。Claudemcpによる分析を提供。',
    'home.searchDemo.videoHeader': 'XBRL Financial API Demo',
    'home.searchDemo.interactiveMode': 'インタラクティブモード',
    'home.searchDemo.videoMode': '動画モード',
    'home.searchDemo.demoVideoTitle': 'デモビデオ',
    'home.searchDemo.demoVideoDescription': 'XBRL Financial APIの実際の動作をご覧ください。企業の財務データを瞬時に取得し、AI分析によるインサイトを提供する様子をデモンストレーションしています。',
    'home.searchDemo.realtimeData': 'リアルタイムデータ',
    'home.searchDemo.realtimeDataDesc': '最新の財務情報を即座に取得',
    'home.searchDemo.aiAnalysis': 'AI分析',
    'home.searchDemo.aiAnalysisDesc': 'Claudeによる高度な解析',
    'home.searchDemo.easyApi': '使いやすいAPI',
    'home.searchDemo.easyApiDesc': 'シンプルなRESTful設計',
    'home.searchDemo.inputPlaceholder': '企業名またはコード',
    'home.searchDemo.analyzing': '分析中...',
    'home.searchDemo.execute': '実行',
    'home.searchDemo.error': 'エラー:',
    'home.searchDemo.responseTime': 'Response time: {time}ms',
    'home.searchDemo.jsonResponse': 'JSON Response',
    'home.searchDemo.analysisResult': '分析結果',
    'home.searchDemo.analysisText': '{company}の財務データを取得しました。ROE {roe}%、時価総額{marketCap}の優良企業です。ESGスコアも{esg}と高く、持続可能な経営を行っています。',
    'home.searchDemo.startMessage': '企業名やコードを入力して分析を開始してください',
    'home.searchDemo.feature1.title': 'AI分析',
    'home.searchDemo.feature1.desc': 'Claude Desktopスタイルの直感的なインターフェース',
    'home.searchDemo.feature2.title': '豊富なデータ',
    'home.searchDemo.feature2.desc': '5年分の有価証券報告書データへのアクセス',
    'home.searchDemo.feature3.title': 'Claudeによる分析',
    'home.searchDemo.feature3.desc': 'データ取得を気軽に行えます。',
    // IndependentFeatureCards component
    'home.features.badge': 'プレミアム機能',
    'home.features.title': 'プロフェッショナル財務分析',
    'home.features.titleSuffix': 'で投資の未来を切り拓く',
    'home.features.subtitle1': '高精度な財務データとユーザーフレンドリーなインターフェースで、',
    'home.features.subtitle2': '投資分析を効率化します。',
    'home.features.feature1.title': 'リアルタイム財務分析',
    'home.features.feature1.description': '詳細な財務指標とデータ分析により、企業の財務状況を深く理解できます',
    'home.features.feature1.highlight1': '最新の財務データをリアルタイム取得',
    'home.features.feature1.highlight2': 'AIによる自動分析レポート生成',
    'home.features.feature1.highlight3': '複数企業の比較分析機能',
    'home.features.feature2.title': '有価証券報告書まとめ',
    'home.features.feature2.description': 'Claudeが有価証券報告書から重要な情報を自動抽出し、分かりやすくまとめます',
    'home.features.feature2.highlight1': '重要項目の自動抽出',
    'home.features.feature2.highlight2': 'エグゼクティブサマリー作成',
    'home.features.feature2.highlight3': 'リスク要因の可視化',
    'home.features.feature3.title': '有価証券報告書データ加工',
    'home.features.feature3.description': 'Claudeによる自動データ加工で、複雑な有価証券報告書データを使いやすい形式に変換',
    'home.features.feature3.highlight1': '構造化データへの自動変換',
    'home.features.feature3.highlight2': 'ExcelやCSVエクスポート',
    'home.features.feature3.highlight3': 'カスタマイズ可能な出力形式',
    'home.features.watchDemo': 'デモ動画を見る',
    'home.features.backToImage': 'イメージに戻す',
    'home.features.viewDetails': '詳細を見る',
    'home.features.cta.title': 'プロフェッショナル機能を体験',
    'home.features.cta.description': 'スタンダードプランを体験してみてください。',
    'home.features.cta.button': 'スタンダードを試す',
    // Pricing page
    'pricing.badge': '透明な料金体系',
    'pricing.title1': 'シンプルで分かりやすい',
    'pricing.title2': '料金プラン',
    'pricing.subtitle1': 'あなたのニーズに合わせて選択できる2つのプラン。',
    'pricing.subtitle2': 'いつでもアップグレード・ダウングレード可能です。',
    'pricing.monthly': '月額プラン',
    'pricing.yearly': '年額プラン',
    'pricing.yearlyDiscount': '20%お得',
    'pricing.popular': '最も人気',
    'pricing.features': '含まれる機能',
    'pricing.limitations': '制限事項',
    'pricing.perMonth': '月',
    'pricing.perYear': '年',
    'pricing.monthlyEquivalent': '月額換算',
    'pricing.noCard': 'クレジットカード不要',
    'pricing.startNow': 'すぐに利用開始',
    'pricing.faqTitle': '料金に関するよくある質問',
    'pricing.faq1.q': 'プラン変更はいつでも可能ですか？',
    'pricing.faq1.a': 'はい、いつでもプランのアップグレード・ダウングレードが可能です。変更は次の請求サイクルから適用されます。',
    'pricing.faq2.q': '支払い方法は何がありますか？',
    'pricing.faq2.a': 'Stripeによる安全な決済システムでクレジットカード決済に対応しています。',
    'pricing.faq3.q': '解約手続きは簡単ですか？',
    'pricing.faq3.a': '管理画面からいつでも簡単に解約できます。解約後も契約期間終了まではサービスをご利用いただけます。',
    'pricing.faq4.q': '年額プランの割引について',
    'pricing.faq4.a': '年額プランをお選びいただくと20%の割引が適用され、大変お得にご利用いただけます。',
    'pricing.plan.freemium.name': 'フリーミアム',
    'pricing.plan.freemium.description': '直近1年間のデータに限定アクセス',
    'pricing.plan.freemium.feature1': '直近1年間の財務データアクセス',
    'pricing.plan.freemium.limitation1': '過去データは1年間のみ',
    'pricing.plan.freemium.button': '無料で始める',
    'pricing.plan.standard.name': 'スタンダード',
    'pricing.plan.standard.description': 'すべてのデータに無制限アクセス',
    'pricing.plan.standard.feature1': '全期間の財務データアクセス',
    'pricing.plan.standard.feature2': '基本的なサポート',
    'pricing.plan.standard.button': 'スタンダードを選択',
    // Login page
    'login.title': 'XBRL API ログイン',
    'login.subtitle': 'アカウントにログインしてAPIキーを管理',
    'login.email': 'メールアドレス',
    'login.password': 'パスワード',
    'login.forgot': 'パスワードを忘れた方',
    'login.button': 'ログイン',
    'login.loading': 'ログイン中...',
    'login.or': 'または',
    'login.noAccount': 'アカウントをお持ちでない方は',
    'login.signup': '新規登録',
    'login.error.required': 'メールアドレスとパスワードを入力してください',
    'login.error.invalid': 'メールアドレスまたはパスワードが正しくありません',
    'login.error.general': 'ログイン中にエラーが発生しました',
    // Signup page
    'signup.title': 'アカウント作成',
    'signup.subtitle': '財務データAPIの利用を開始して、ビジネスの可能性を広げましょう',
    'signup.plan.title': 'プランを選択',
    'signup.plan.subtitle': 'あなたのビジネスに最適なプランをお選びください',
    'signup.plan.monthly': '月額',
    'signup.plan.yearly': '年額',
    'signup.plan.yearlyDiscount': '20%お得',
    'signup.plan.recommended': 'おすすめ',
    'signup.plan.freemium.name': 'フリーミアム',
    'signup.plan.freemium.description': '直近1年間のデータに限定アクセス',
    'signup.plan.freemium.feature1': '直近1年間の財務データアクセス',
    'signup.plan.standard.name': 'スタンダード',
    'signup.plan.standard.description': 'すべてのデータに無制限アクセス',
    'signup.plan.standard.feature1': '全期間の財務データアクセス',
    'signup.plan.standard.feature2': 'APIアクセス',
    'signup.plan.perMonth': '/月',
    'signup.plan.perYear': '/年',
    'signup.plan.monthlyEquivalent': '月額換算',
    'signup.account.title': 'アカウント情報',
    'signup.account.subtitle': '必要な情報を入力してください',
    'signup.name': 'お名前',
    'signup.name.placeholder': '山田太郎',
    'signup.company': '会社名',
    'signup.company.placeholder': '株式会社サンプル',
    'signup.email': 'メールアドレス',
    'signup.email.placeholder': 'example@company.com',
    'signup.password': 'パスワード',
    'signup.password.placeholder': 'パスワードを入力',
    'signup.password.requirements': 'パスワード要件：',
    'signup.password.length': '8文字以上',
    'signup.password.uppercase': '大文字を含む (A-Z)',
    'signup.password.lowercase': '小文字を含む (a-z)',
    'signup.password.number': '数字を含む (0-9)',
    'signup.password.special': '特殊文字を含む (!@#$%など)',
    'signup.confirmPassword': 'パスワード確認',
    'signup.confirmPassword.placeholder': 'パスワードを再入力',
    'signup.terms': '',
    'signup.terms.link': '利用規約',
    'signup.terms.and': 'と',
    'signup.privacy.link': 'プライバシーポリシー',
    'signup.agreeTerms': 'に同意します',
    'signup.investment.title': '投資助言に関する重要な注意事項',
    'signup.investment.text': '当サービスは投資助言業ではなく、情報提供のみを行います。投資判断はお客様ご自身の責任で行ってください。データの正確性は保証されません。',
    'signup.button.free': '無料アカウントを作成',
    'signup.button.paid': 'アカウント作成',
    'signup.button.loading': 'アカウントを作成中...',
    'signup.hasAccount': 'すでにアカウントをお持ちですか？',
    'signup.login': 'ログイン',
    'signup.error.passwordMismatch': 'パスワードが一致しません',
    'signup.error.terms': '利用規約に同意してください',
    'signup.error.investment': '投資助言に関する注意事項をご確認ください',
    'signup.error.passwordLength': 'パスワードは8文字以上で入力してください',
    'signup.error.passwordUppercase': 'パスワードには少なくとも1つの大文字（A-Z）を含めてください',
    'signup.error.passwordLowercase': 'パスワードには少なくとも1つの小文字（a-z）を含めてください',
    'signup.error.passwordNumber': 'パスワードには少なくとも1つの数字（0-9）を含めてください',
    'signup.error.passwordSpecial': 'パスワードには少なくとも1つの特殊文字（!@#$%など）を含めてください',
    'signup.error.failed': 'アカウント作成に失敗しました',
    'signup.error.general': 'アカウント作成中にエラーが発生しました',
    // Dashboard page
    'dashboard.title': 'ダッシュボード',
    'dashboard.subtitle': 'アカウント設定と管理機能',
    'dashboard.loading': '読み込み中...',
    'dashboard.auth.checking': '認証状態を確認中...',
    'dashboard.auth.required': 'ログインが必要です',
    'dashboard.auth.redirecting': 'リダイレクト中...',
    // Account Settings (Dashboard tabs)
    'settings.tabs.profile': 'プロフィール',
    'settings.tabs.plan': 'プラン管理',
    'settings.tabs.api': 'APIキー',
    'settings.tabs.logout': 'ログアウト',
    'settings.profile.description': 'アカウントに紐づく基本情報を管理します。',
    'settings.profile.email': 'メールアドレス',
    'settings.profile.name': 'ユーザー名',
    'settings.profile.company': '会社名',
    'settings.profile.save': '変更を保存',
    'settings.profile.success': 'プロフィール情報を更新しました。',
    'settings.plan.description': '契約中のプランや請求履歴を確認し、プラン変更をリクエストできます。',
    'settings.plan.current': '現在のプラン',
    'settings.plan.price': '料金',
    'settings.plan.status': 'アクティブ',
    'settings.plan.nextBilling': '次回請求日',
    'settings.plan.freemium.name': 'フリーミアム',
    'settings.plan.freemium.description': '個人投資家や検証用途向け',
    'settings.plan.freemium.feature1': '直近1年間の財務データ',
    'settings.plan.freemium.feature2': '月間5,000リクエスト',
    'settings.plan.freemium.feature3': '標準サポート',
    'settings.plan.standard.name': 'スタンダード',
    'settings.plan.standard.description': '本番利用向けの標準プラン',
    'settings.plan.standard.feature1': '全期間の財務データ',
    'settings.plan.standard.feature2': 'APIリクエスト無制限',
    'settings.plan.standard.feature3': '優先サポート',
    'settings.plan.standard.feature4': 'レポート生成機能',
    'settings.plan.recommended': 'おすすめ',
    'settings.plan.currentPlan': '現在のプラン',
    'settings.plan.selected': '選択中',
    'settings.plan.clickSelect': 'クリックして選択',
    'settings.plan.update': 'プランを更新',
    'settings.plan.billingHistory': '請求履歴',
    'settings.plan.noBilling': '請求履歴はありません',
    'settings.plan.success.current': '既に{plan}プランをご利用中です。',
    'settings.plan.success.requested': 'プラン変更のリクエストを受け付けました。',
    'settings.api.description': 'APIキーの発行・管理・削除が行えます。',
    'settings.api.newKey': '新しいAPIキー',
    'settings.api.newKeyName': '新しいAPIキー名',
    'settings.api.keyNamePlaceholder': '例: Production Key',
    'settings.api.reload': '再読み込み',
    'settings.api.create': 'APIキーを作成',
    'settings.api.creating': '作成中...',
    'settings.api.list': 'APIキー一覧',
    'settings.api.count': '{count} 件',
    'settings.api.loading': 'APIキーを読み込み中...',
    'settings.api.noKeys': 'まだAPIキーがありません。上のフォームから作成できます。',
    'settings.api.active': 'アクティブ',
    'settings.api.created': '作成',
    'settings.api.lastUsed': '最終使用',
    'settings.api.notUsed': '未使用',
    'settings.api.copy': 'コピー',
    'settings.api.delete': '削除',
    'settings.api.success.created': '新しいAPIキーを作成しました。',
    'settings.api.success.copied': 'APIキーをコピーしました。',
    'settings.api.success.deleted': 'APIキーを削除しました。',
    'settings.api.error.load': 'APIキーの読み込みに失敗しました。',
    'settings.api.error.create': 'APIキーの作成に失敗しました。',
    'settings.api.error.delete': 'APIキーの削除に失敗しました。',
    'settings.api.error.loginRequired': 'ログインが必要です。',
    'settings.api.newKeyAlert': '新しいAPIキー',
    'settings.api.newKeyWarning': '⚠️ このキーは一度しか表示されません。安全な場所に保存してください。',
    'settings.dialog.deleteKey.title': 'APIキーの削除',
    'settings.dialog.deleteKey.message': 'APIキー「{name}」を削除しますか？この操作は取り消せません。',
    'settings.dialog.deleteKey.confirm': '削除',
    'settings.dialog.deleteKey.cancel': 'キャンセル',
    'settings.dialog.logout.title': 'ログアウト',
    'settings.dialog.logout.message': 'ログアウトしてもよろしいですか？',
    'settings.dialog.logout.confirm': 'ログアウト',
    'settings.dialog.logout.cancel': 'キャンセル',
    // AccountSettings component - comprehensive translations
    'dashboard.settings.tabs.profile': 'プロフィール',
    'dashboard.settings.tabs.plan': 'プラン管理',
    'dashboard.settings.tabs.api': 'APIキー',
    'dashboard.settings.tabs.logout': 'ログアウト',
    'dashboard.settings.profile.description': 'アカウントに紐づく基本情報を管理します。',
    'dashboard.settings.profile.currentInfoTitle': '現在の登録情報',
    'dashboard.settings.profile.emailLabel': 'メールアドレス',
    'dashboard.settings.profile.emailPlaceholder': 'your@email.com',
    'dashboard.settings.profile.nameLabel': 'ユーザー名',
    'dashboard.settings.profile.namePlaceholder': '田中太郎',
    'dashboard.settings.profile.companyLabel': '会社名',
    'dashboard.settings.profile.companyPlaceholder': '株式会社サンプル',
    'dashboard.settings.profile.saveButton': '変更を保存',
    'dashboard.settings.profile.saving': '保存中...',
    'dashboard.settings.profile.successMessage': 'プロフィール情報を更新しました。',
    'dashboard.settings.profile.errorUpdate': 'プロフィール情報の更新に失敗しました。',
    'dashboard.settings.profile.noChanges': '変更はありません。',
    'dashboard.settings.profile.rateLimitError': '短時間に複数回更新できません。しばらく待ってから再度お試しください。',
    'dashboard.settings.profile.unsavedChanges': '未保存の変更があります',
    'dashboard.settings.profile.emailChangeNote': '※ メールアドレス変更後、新しいメールアドレスに確認メールが送信されます。',
    'dashboard.settings.profile.emailConfirmationSent': '確認メールを送信しました。新しいメールアドレスで確認リンクをクリックしてください。',
    'dashboard.settings.plan.description': '契約中のプランや請求履歴を確認し、プラン変更をリクエストできます。',
    'dashboard.settings.plan.currentPlanStatus': 'アクティブ',
    'dashboard.settings.plan.nextBillingLabel': '次回請求日:',
    'dashboard.settings.plan.freemium.name': 'フリーミアム',
    'dashboard.settings.plan.freemium.price': '¥0/月',
    'dashboard.settings.plan.freemium.description': '個人投資家や検証用途向け',
    'dashboard.settings.plan.freemium.feature1': '直近1年間の財務データ',
    'dashboard.settings.plan.freemium.feature2': '月間5,000リクエスト',
    'dashboard.settings.plan.freemium.feature3': '標準サポート',
    'dashboard.settings.plan.standard.name': 'スタンダード',
    'dashboard.settings.plan.standard.price': '¥2,980/月',
    'dashboard.settings.plan.standard.description': '本番利用向けの標準プラン',
    'dashboard.settings.plan.standard.feature1': '全期間の財務データ',
    'dashboard.settings.plan.standard.feature2': 'APIリクエスト無制限',
    'dashboard.settings.plan.standard.feature3': '優先サポート',
    'dashboard.settings.plan.standard.feature4': 'レポート生成機能',
    'dashboard.settings.plan.recommendedBadge': 'おすすめ',
    'dashboard.settings.plan.currentPlanBadge': '現在のプラン',
    'dashboard.settings.plan.selectedLabel': '選択中',
    'dashboard.settings.plan.clickSelectLabel': 'クリックして選択',
    'dashboard.settings.plan.updateButton': 'プランを更新',
    'dashboard.settings.plan.billingHistoryTitle': '請求履歴',
    'dashboard.settings.plan.noBillingHistory': '請求履歴はありません',
    'dashboard.settings.plan.successCurrentPlan': '既に{name}プランをご利用中です。',
    'dashboard.settings.plan.successPlanChange': 'プラン変更のリクエストを受け付けました。',
    'dashboard.settings.api.description': 'APIキーの発行・管理・削除が行えます。',
    'dashboard.settings.api.newKeyTitle': '新しいAPIキー',
    'dashboard.settings.api.newKeyLabel': '新しいAPIキー名',
    'dashboard.settings.api.newKeyPlaceholder': '例: Production Key',
    'dashboard.settings.api.newKeyWarning': '⚠️ このキーは一度しか表示されません。安全な場所に保存してください。',
    'dashboard.settings.api.reloadButton': '再読み込み',
    'dashboard.settings.api.createButton': 'APIキーを作成',
    'dashboard.settings.api.creatingButton': '作成中...',
    'dashboard.settings.api.listTitle': 'APIキー一覧',
    'dashboard.settings.api.countLabel': '{count} 件',
    'dashboard.settings.api.loadingMessage': 'APIキーを読み込み中...',
    'dashboard.settings.api.noKeysMessage': 'まだAPIキーがありません。上のフォームから作成できます。',
    'dashboard.settings.api.activeBadge': 'アクティブ',
    'dashboard.settings.api.createdLabel': '作成:',
    'dashboard.settings.api.lastUsedLabel': '最終使用:',
    'dashboard.settings.api.notUsedLabel': '未使用',
    'dashboard.settings.api.copyButton': 'コピー',
    'dashboard.settings.api.deleteButton': '削除',
    'dashboard.settings.api.successCreated': '新しいAPIキーを作成しました。',
    'dashboard.settings.api.successCopied': 'APIキーをコピーしました。',
    'dashboard.settings.api.successDeleted': 'APIキーを削除しました。',
    'dashboard.settings.api.errorLoad': 'APIキーの読み込みに失敗しました。',
    'dashboard.settings.api.errorCreate': 'APIキーの作成に失敗しました。',
    'dashboard.settings.api.errorDelete': 'APIキーの削除に失敗しました。',
    'dashboard.settings.api.errorLoginRequired': 'ログインが必要です。',
    'dashboard.settings.api.errorSessionNotFound': '認証セッションが見つかりません。再度ログインしてください。',
    'dashboard.settings.dialog.deleteKey.title': 'APIキーの削除',
    'dashboard.settings.dialog.deleteKey.message': 'APIキー「{name}」を削除しますか？この操作は取り消せません。',
    'dashboard.settings.dialog.deleteKey.confirm': '削除',
    'dashboard.settings.dialog.deleteKey.cancel': 'キャンセル',
    'dashboard.settings.dialog.logout.title': 'ログアウト',
    'dashboard.settings.dialog.logout.message': 'ログアウトしてもよろしいですか？',
    'dashboard.settings.dialog.logout.confirm': 'ログアウト',
    'dashboard.settings.dialog.logout.cancel': 'キャンセル',
    'dashboard.settings.auth.checking': '認証状態を確認中...',
    'dashboard.settings.auth.required': 'ログインが必要です',
    'dashboard.settings.auth.redirecting': 'リダイレクト中...',
    // API Key Modal
    'apiKeyModal.title': 'APIキーが発行されました',
    'apiKeyModal.subtitle': 'このキーは二度と表示されません。必ず安全な場所に保存してください。',
    'apiKeyModal.yourKey': 'あなたのAPIキー',
    'apiKeyModal.copied': 'コピーしました！',
    'apiKeyModal.copyButton': 'APIキーをコピー',
    'apiKeyModal.warning.title': '重要な注意事項',
    'apiKeyModal.warning.item1': '• このキーは今回のみ表示されます',
    'apiKeyModal.warning.item2': '• 他人と共有しないでください',
    'apiKeyModal.warning.item3': '• 紛失した場合は新しいキーを再発行してください',
    'apiKeyModal.continue': 'ダッシュボードへ進む',
    'apiKeyModal.copy': 'コピー',
    // Documentation page
    'docs.page.title': 'API ドキュメント',
    'docs.page.subtitle': '財務データAPIの使用方法とガイドライン',
    'docs.nav.tableOfContents': '目次',
    'docs.nav.support': 'サポート',
    'docs.nav.support.description': 'ご不明な点がございましたら、お気軽にお問い合わせください。',
    'docs.nav.support.contact': 'サポートに連絡',
    'docs.section.gettingStarted': 'はじめに',
    'docs.section.gettingStarted.introduction': '概要',
    'docs.section.gettingStarted.quickStart': 'クイックスタート',
    'docs.section.gettingStarted.authentication': '認証',
    'docs.section.apiReference': 'API リファレンス',
    'docs.section.apiReference.companies': '企業データ',
    'docs.section.apiReference.financials': '財務データ',
    'docs.section.apiReference.analysis': '分析データ',
    'docs.section.guides': 'ガイド',
    'docs.section.guides.dataAnalysis': 'データ分析',
    'docs.section.guides.reporting': 'レポート作成',
    'docs.section.guides.automation': '自動化',
    'docs.section.examples': '使用例',
    'docs.section.examples.python': 'Python',
    'docs.section.examples.javascript': 'JavaScript',
    'docs.section.examples.curl': 'cURL',
    'docs.introduction.title': '概要',
    'docs.introduction.description1': '財務データAPIは、日本の上場企業の財務情報や企業データにアクセスするためのRESTful APIです。',
    'docs.introduction.description2': '有価証券報告書のデータをClaudeが解析し、構造化された形式で提供します。',
    'docs.introduction.features.title': '主な機能',
    'docs.introduction.features.item1': '企業の基本情報とプロフィール',
    'docs.introduction.features.item2': '財務諸表データ（貸借対照表、損益計算書、キャッシュフロー計算書）',
    'docs.introduction.features.item3': 'Claudeによる財務分析とインサイト',
    'docs.introduction.features.item4': '有価証券報告書の自動要約',
    'docs.quickstart.title': 'クイックスタート',
    'docs.quickstart.step1.title': '1. APIキーの取得',
    'docs.quickstart.step1.description': 'まず、ダッシュボードからAPIキーを作成してください。',
    'docs.quickstart.step1.path': 'ダッシュボード → アカウント設定 → APIキー → 新しいキーを作成',
    'docs.quickstart.step2.title': '2. 最初のリクエスト',
    'docs.quickstart.step2.description': '企業データを取得する基本的な例：',
    'docs.quickstart.step3.title': '3. レスポンス形式',
    'docs.quickstart.step3.description': 'APIは以下の形式でJSONレスポンスを返します：',
    'docs.authentication.title': '認証',
    'docs.authentication.description': 'すべてのAPIリクエストには、HTTPヘッダーにBearerトークン形式でAPIキーを含める必要があります。',
    'docs.authentication.security.title': 'セキュリティについて',
    'docs.authentication.security.description': 'APIキーは機密情報です。クライアントサイドのコードに直接記述せず、サーバーサイドまたは環境変数として安全に管理してください。',
    'docs.apiReference.title': 'API リファレンス',
    'docs.apiReference.endpoint1.description': '企業一覧を取得',
    'docs.apiReference.endpoint1.param1.name': 'industry',
    'docs.apiReference.endpoint1.param1.description': '業界でフィルタ（オプション）',
    'docs.apiReference.endpoint1.param2.name': 'market',
    'docs.apiReference.endpoint1.param2.description': '市場でフィルタ（オプション）',
    'docs.apiReference.endpoint1.param3.name': 'limit',
    'docs.apiReference.endpoint1.param3.description': '取得件数（デフォルト: 20）',
    'docs.apiReference.endpoint2.description': '特定企業の詳細情報を取得',
    'docs.apiReference.endpoint2.param1.name': 'id',
    'docs.apiReference.endpoint2.param1.description': '企業ID（必須）',
    'docs.apiReference.endpoint3.description': '企業の財務データを取得',
    'docs.apiReference.endpoint3.param1.name': 'id',
    'docs.apiReference.endpoint3.param1.description': '企業ID（必須）',
    'docs.apiReference.endpoint3.param2.name': 'year',
    'docs.apiReference.endpoint3.param2.description': '対象年度（オプション）',
    'docs.apiReference.endpoint3.param3.name': 'quarter',
    'docs.apiReference.endpoint3.param3.description': '四半期（1-4、オプション）',
    'docs.apiReference.parameters': 'パラメータ',
    'docs.apiReference.parameterTable.name': '名前',
    'docs.apiReference.parameterTable.type': '型',
    'docs.apiReference.parameterTable.description': '説明',
    'docs.examples.title': '使用例',
    'docs.dataAnalysis.title': 'データ分析ガイド',
    'docs.dataAnalysis.claude.title': 'Claudeによる分析機能',
    'docs.dataAnalysis.claude.description': '有価証券報告書を自動分析し、重要なインサイトを提供',
    'docs.dataAnalysis.feature1.title': '財務分析',
    'docs.dataAnalysis.feature1.description': '収益性、成長性、安全性の指標を自動計算',
    'docs.dataAnalysis.feature2.title': 'リスク評価',
    'docs.dataAnalysis.feature2.description': '企業の潜在的リスクを特定・評価',
    'docs.dataAnalysis.feature3.title': '業界比較',
    'docs.dataAnalysis.feature3.description': '同業他社との詳細な比較分析',
    'docs.dataAnalysis.feature4.title': '予測モデル',
    'docs.dataAnalysis.feature4.description': '将来の業績予測とシナリオ分析',
    'docs.dataAnalysis.usage.title': '分析データの活用方法',
    'docs.dataAnalysis.usage1.title': '投資判断',
    'docs.dataAnalysis.usage1.description': '財務指標と分析結果を基にした投資戦略の策定',
    'docs.dataAnalysis.usage2.title': 'レポート作成',
    'docs.dataAnalysis.usage2.description': 'クライアント向けの詳細な財務分析レポート',
    'docs.dataAnalysis.usage3.title': 'リスク監視',
    'docs.dataAnalysis.usage3.description': '定期的な財務健全性チェックとアラート設定',
    'docs.faq.title': 'よくある質問',
    'docs.faq.q1': 'APIの利用制限はありますか？',
    'docs.faq.a1': 'プランに応じて月間のリクエスト数に制限があります。スタンダードプランでは月間10,000リクエストまで利用可能です。',
    'docs.faq.q2': 'データの更新頻度はどのくらいですか？',
    'docs.faq.a2': '有価証券報告書の提出後、通常24時間以内にデータが更新されます。四半期報告書は提出から48時間以内です。',
    'docs.faq.q3': 'どの企業のデータが利用できますか？',
    'docs.faq.a3': '東証プライム、スタンダード、グロース市場に上場している全企業のデータを提供しています。',
    'docs.faq.q4': 'APIキーが漏洩した場合はどうすればよいですか？',
    'docs.faq.a4': 'すぐにダッシュボードから該当のAPIキーを削除し、新しいAPIキーを作成してください。',
  },
  en: {
    'nav.pricing': 'Pricing',
    'nav.docs': 'Documentation',
    'nav.login': 'Login',
    'nav.signup': 'Get Started',
    'hero.badge': 'Professional Financial Data API',
    'hero.title1': 'Next-Generation Financial',
    'hero.title2': 'Data Platform',
    'hero.description1': 'Instantly access corporate financial information with Japan\'s largest XBRL financial database.',
    'hero.description2': 'Efficiently analyze data for informed investment decisions.',
    'hero.cta.signup': 'Start Free Trial',
    'hero.cta.login': 'Login',
    'hero.cta.demo': 'Live Demo',
    'hero.stat1': '3,800+',
    'hero.stat1Label': 'Listed Companies',
    'hero.stat2': 'Securities Report Data',
    'hero.stat2Label': 'Historical Data',
    'faq.title': 'Frequently Asked Questions',
    'faq.description': 'Answers to common questions about XBRL Financial API',
    'faq.q1': 'Does this service provide investment advice?',
    'faq.a1': 'No, this service is not an investment advisory business. We provide information only as a financial data analysis tool and do not make specific investment decisions or recommendations. Final investment decisions must be made at your own responsibility.',
    'faq.q2': 'What kind of data can I access?',
    'faq.a2': 'We provide financial data, performance indicators, and company information extracted from securities reports of listed companies in Japan. All data is based on publicly available information.',
    'faq.q3': 'Are there any API usage limits?',
    'faq.a3': 'The Freemium plan provides access to data from the past year, while the Standard plan provides access to all available data.',
    'faq.q4': 'Is data accuracy guaranteed?',
    'faq.a4': 'While we provide data based on publicly available securities reports, we do not guarantee the accuracy or completeness of the data. For important investment decisions, please always verify primary sources.',
    'faq.q5': 'Which companies\' data is available?',
    'faq.a5': 'We provide data for companies listed on the Tokyo Stock Exchange Prime, Standard, and Growth markets. Target companies are updated regularly.',
    'faq.q6': 'Is commercial use allowed?',
    'faq.a6': 'Yes, commercial use is permitted. However, we assume no responsibility for any damages resulting from selling acquired data to third parties or from AI analysis results.',
    'footer.copyright': '© 2025 Financial Information next (FIN). All rights reserved.',
    'footer.github': 'GitHub',
    // Login page (alternative /login route)
    'login2.title': 'Login to Your Account',
    'login2.orCreate': 'or',
    'login2.createAccount': 'Create a Free Account',
    'login2.email': 'Email',
    'login2.password': 'Password',
    'login2.emailPlaceholder': 'your@email.com',
    'login2.passwordPlaceholder': 'Enter your password',
    'login2.rememberMe': 'Remember me',
    'login2.forgotPassword': 'Forgot password?',
    'login2.loginButton': 'Login',
    'login2.loggingIn': 'Logging in...',
    'login2.noAccount': 'Don\'t have an account?',
    'login2.signupLink': 'Sign up for free',
    'login2.error.invalid': 'Invalid email or password',
    'login2.error.general': 'An error occurred during login',
    // Pricing page
    'pricing.badge': 'Transparent Pricing',
    'pricing.title1': 'Simple and Clear',
    'pricing.title2': 'Pricing Plans',
    'pricing.subtitle1': 'Choose from two plans that fit your needs.',
    'pricing.subtitle2': 'Upgrade or downgrade anytime.',
    'pricing.monthly': 'Monthly Plan',
    'pricing.yearly': 'Annual Plan',
    'pricing.yearlyDiscount': '20% Off',
    'pricing.popular': 'Most Popular',
    'pricing.features': 'Included Features',
    'pricing.limitations': 'Limitations',
    'pricing.perMonth': 'month',
    'pricing.perYear': 'year',
    'pricing.monthlyEquivalent': 'Monthly equivalent',
    'pricing.noCard': 'No credit card required',
    'pricing.startNow': 'Start immediately',
    'pricing.faqTitle': 'Pricing FAQs',
    'pricing.faq1.q': 'Can I change plans anytime?',
    'pricing.faq1.a': 'Yes, you can upgrade or downgrade anytime. Changes will be applied from the next billing cycle.',
    'pricing.faq2.q': 'What payment methods are available?',
    'pricing.faq2.a': 'We support credit card payments through Stripe\'s secure payment system.',
    'pricing.faq3.q': 'Is cancellation easy?',
    'pricing.faq3.a': 'You can easily cancel from the dashboard anytime. You can continue using the service until the end of your contract period after cancellation.',
    'pricing.faq4.q': 'About the annual plan discount',
    'pricing.faq4.a': 'Choose the annual plan and get 20% off for great value.',
    'pricing.plan.freemium.name': 'Freemium',
    'pricing.plan.freemium.description': 'Limited access to data from the past year',
    'pricing.plan.freemium.feature1': 'Access to financial data from the past year',
    'pricing.plan.freemium.limitation1': 'Historical data limited to 1 year',
    'pricing.plan.freemium.button': 'Get Started Free',
    'pricing.plan.standard.name': 'Standard',
    'pricing.plan.standard.description': 'Unlimited access to all data',
    'pricing.plan.standard.feature1': 'Access to all-time financial data',
    'pricing.plan.standard.feature2': 'Basic support',
    'pricing.plan.standard.button': 'Choose Standard',
    // Login page
    'login.title': 'XBRL API Login',
    'login.subtitle': 'Login to your account to manage API keys',
    'login.email': 'Email Address',
    'login.password': 'Password',
    'login.forgot': 'Forgot your password?',
    'login.button': 'Login',
    'login.loading': 'Logging in...',
    'login.or': 'or',
    'login.noAccount': 'Don\'t have an account?',
    'login.signup': 'Sign up',
    'login.error.required': 'Please enter email address and password',
    'login.error.invalid': 'Email address or password is incorrect',
    'login.error.general': 'An error occurred during login',
    // Signup page
    'signup.title': 'Create Account',
    'signup.subtitle': 'Start using the financial data API and expand your business possibilities',
    'signup.plan.title': 'Select a Plan',
    'signup.plan.subtitle': 'Choose the plan that best fits your business',
    'signup.plan.monthly': 'Monthly',
    'signup.plan.yearly': 'Annual',
    'signup.plan.yearlyDiscount': '20% Off',
    'signup.plan.recommended': 'Recommended',
    'signup.plan.freemium.name': 'Freemium',
    'signup.plan.freemium.description': 'Limited access to data from the past year',
    'signup.plan.freemium.feature1': 'Access to financial data from the past year',
    'signup.plan.standard.name': 'Standard',
    'signup.plan.standard.description': 'Unlimited access to all data',
    'signup.plan.standard.feature1': 'Access to all-time financial data',
    'signup.plan.standard.feature2': 'API access',
    'signup.plan.perMonth': '/month',
    'signup.plan.perYear': '/year',
    'signup.plan.monthlyEquivalent': 'Monthly equivalent',
    'signup.account.title': 'Account Information',
    'signup.account.subtitle': 'Please enter the required information',
    'signup.name': 'Name',
    'signup.name.placeholder': 'Taro Yamada',
    'signup.company': 'Company Name',
    'signup.company.placeholder': 'Sample Corporation',
    'signup.email': 'Email Address',
    'signup.email.placeholder': 'example@company.com',
    'signup.password': 'Password',
    'signup.password.placeholder': 'Enter password',
    'signup.password.requirements': 'Password requirements:',
    'signup.password.length': 'At least 8 characters',
    'signup.password.uppercase': 'Include uppercase (A-Z)',
    'signup.password.lowercase': 'Include lowercase (a-z)',
    'signup.password.number': 'Include number (0-9)',
    'signup.password.special': 'Include special character (!@#$%, etc.)',
    'signup.confirmPassword': 'Confirm Password',
    'signup.confirmPassword.placeholder': 'Re-enter password',
    'signup.terms': 'I agree to the',
    'signup.terms.link': 'Terms of Service',
    'signup.terms.and': 'and',
    'signup.privacy.link': 'Privacy Policy',
    'signup.agreeTerms': '',
    'signup.investment.title': 'Important Notice Regarding Investment Advice',
    'signup.investment.text': 'This service is not an investment advisory business and provides information only. Investment decisions are your own responsibility. Data accuracy is not guaranteed.',
    'signup.button.free': 'Create Free Account',
    'signup.button.paid': 'Create Account',
    'signup.button.loading': 'Creating account...',
    'signup.hasAccount': 'Already have an account?',
    'signup.login': 'Login',
    'signup.error.passwordMismatch': 'Passwords do not match',
    'signup.error.terms': 'Please agree to the Terms of Service',
    'signup.error.investment': 'Please confirm the investment advice notice',
    'signup.error.passwordLength': 'Password must be at least 8 characters',
    'signup.error.passwordUppercase': 'Password must include at least one uppercase letter (A-Z)',
    'signup.error.passwordLowercase': 'Password must include at least one lowercase letter (a-z)',
    'signup.error.passwordNumber': 'Password must include at least one number (0-9)',
    'signup.error.passwordSpecial': 'Password must include at least one special character (!@#$%, etc.)',
    'signup.error.failed': 'Failed to create account',
    'signup.error.general': 'An error occurred while creating account',
    // Dashboard page
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Account settings and management features',
    'dashboard.loading': 'Loading...',
    'dashboard.auth.checking': 'Checking authentication status...',
    'dashboard.auth.required': 'Login required',
    'dashboard.auth.redirecting': 'Redirecting...',
    // Account Settings (Dashboard tabs)
    'settings.tabs.profile': 'Profile',
    'settings.tabs.plan': 'Plan Management',
    'settings.tabs.api': 'API Keys',
    'settings.tabs.logout': 'Logout',
    'settings.profile.description': 'Manage basic information associated with your account.',
    'settings.profile.email': 'Email Address',
    'settings.profile.name': 'Username',
    'settings.profile.company': 'Company Name',
    'settings.profile.save': 'Save Changes',
    'settings.profile.success': 'Profile information updated.',
    'settings.plan.description': 'Check your current plan and billing history, and request plan changes.',
    'settings.plan.current': 'Current Plan',
    'settings.plan.price': 'Price',
    'settings.plan.status': 'Active',
    'settings.plan.nextBilling': 'Next billing date',
    'settings.plan.freemium.name': 'Freemium',
    'settings.plan.freemium.description': 'For individual investors and verification',
    'settings.plan.freemium.feature1': 'Financial data from the past year',
    'settings.plan.freemium.feature2': '5,000 requests per month',
    'settings.plan.freemium.feature3': 'Standard support',
    'settings.plan.standard.name': 'Standard',
    'settings.plan.standard.description': 'Standard plan for production use',
    'settings.plan.standard.feature1': 'All-time financial data',
    'settings.plan.standard.feature2': 'Unlimited API requests',
    'settings.plan.standard.feature3': 'Priority support',
    'settings.plan.standard.feature4': 'Report generation feature',
    'settings.plan.recommended': 'Recommended',
    'settings.plan.currentPlan': 'Current Plan',
    'settings.plan.selected': 'Selected',
    'settings.plan.clickSelect': 'Click to select',
    'settings.plan.update': 'Update Plan',
    'settings.plan.billingHistory': 'Billing History',
    'settings.plan.noBilling': 'No billing history',
    'settings.plan.success.current': 'You are already using the {plan} plan.',
    'settings.plan.success.requested': 'Plan change request has been received.',
    'settings.api.description': 'Issue, manage, and delete API keys.',
    'settings.api.newKey': 'New API Key',
    'settings.api.newKeyName': 'New API Key Name',
    'settings.api.keyNamePlaceholder': 'e.g., Production Key',
    'settings.api.reload': 'Reload',
    'settings.api.create': 'Create API Key',
    'settings.api.creating': 'Creating...',
    'settings.api.list': 'API Key List',
    'settings.api.count': '{count} items',
    'settings.api.loading': 'Loading API keys...',
    'settings.api.noKeys': 'No API keys yet. You can create one from the form above.',
    'settings.api.active': 'Active',
    'settings.api.created': 'Created',
    'settings.api.lastUsed': 'Last used',
    'settings.api.notUsed': 'Not used',
    'settings.api.copy': 'Copy',
    'settings.api.delete': 'Delete',
    'settings.api.success.created': 'New API key created.',
    'settings.api.success.copied': 'API key copied.',
    'settings.api.success.deleted': 'API key deleted.',
    'settings.api.error.load': 'Failed to load API keys.',
    'settings.api.error.create': 'Failed to create API key.',
    'settings.api.error.delete': 'Failed to delete API key.',
    'settings.api.error.loginRequired': 'Login required.',
    'settings.api.newKeyAlert': 'New API Key',
    'settings.api.newKeyWarning': 'This key will only be displayed once. Please save it in a safe place.',
    'settings.dialog.deleteKey.title': 'Delete API Key',
    'settings.dialog.deleteKey.message': 'Are you sure you want to delete the API key "{name}"? This action cannot be undone.',
    'settings.dialog.deleteKey.confirm': 'Delete',
    'settings.dialog.deleteKey.cancel': 'Cancel',
    'settings.dialog.logout.title': 'Logout',
    'settings.dialog.logout.message': 'Are you sure you want to logout?',
    'settings.dialog.logout.confirm': 'Logout',
    'settings.dialog.logout.cancel': 'Cancel',
    // AccountSettings component - comprehensive translations
    'dashboard.settings.tabs.profile': 'Profile',
    'dashboard.settings.tabs.plan': 'Plan Management',
    'dashboard.settings.tabs.api': 'API Keys',
    'dashboard.settings.tabs.logout': 'Logout',
    'dashboard.settings.profile.description': 'Manage basic information associated with your account.',
    'dashboard.settings.profile.currentInfoTitle': 'Current Registration Information',
    'dashboard.settings.profile.emailLabel': 'Email Address',
    'dashboard.settings.profile.emailPlaceholder': 'your@email.com',
    'dashboard.settings.profile.nameLabel': 'Username',
    'dashboard.settings.profile.namePlaceholder': 'John Doe',
    'dashboard.settings.profile.companyLabel': 'Company Name',
    'dashboard.settings.profile.companyPlaceholder': 'Sample Corporation',
    'dashboard.settings.profile.saveButton': 'Save Changes',
    'dashboard.settings.profile.saving': 'Saving...',
    'dashboard.settings.profile.successMessage': 'Profile information updated.',
    'dashboard.settings.profile.errorUpdate': 'Failed to update profile information.',
    'dashboard.settings.profile.noChanges': 'No changes to save.',
    'dashboard.settings.profile.rateLimitError': 'Too many update requests. Please wait a moment and try again.',
    'dashboard.settings.profile.unsavedChanges': 'You have unsaved changes',
    'dashboard.settings.profile.emailChangeNote': '* A confirmation email will be sent to your new email address after changing it.',
    'dashboard.settings.profile.emailConfirmationSent': 'Confirmation email sent. Please click the link in your new email address to verify.',
    'dashboard.settings.plan.description': 'Check your current plan and billing history, and request plan changes.',
    'dashboard.settings.plan.currentPlanStatus': 'Active',
    'dashboard.settings.plan.nextBillingLabel': 'Next billing date:',
    'dashboard.settings.plan.freemium.name': 'Freemium',
    'dashboard.settings.plan.freemium.price': '$0/month',
    'dashboard.settings.plan.freemium.description': 'For individual investors and verification',
    'dashboard.settings.plan.freemium.feature1': 'Financial data from the past year',
    'dashboard.settings.plan.freemium.feature2': '5,000 requests per month',
    'dashboard.settings.plan.freemium.feature3': 'Standard support',
    'dashboard.settings.plan.standard.name': 'Standard',
    'dashboard.settings.plan.standard.price': '$29/month',
    'dashboard.settings.plan.standard.description': 'Standard plan for production use',
    'dashboard.settings.plan.standard.feature1': 'All-time financial data',
    'dashboard.settings.plan.standard.feature2': 'Unlimited API requests',
    'dashboard.settings.plan.standard.feature3': 'Priority support',
    'dashboard.settings.plan.standard.feature4': 'Report generation feature',
    'dashboard.settings.plan.recommendedBadge': 'Recommended',
    'dashboard.settings.plan.currentPlanBadge': 'Current Plan',
    'dashboard.settings.plan.selectedLabel': 'Selected',
    'dashboard.settings.plan.clickSelectLabel': 'Click to select',
    'dashboard.settings.plan.updateButton': 'Update Plan',
    'dashboard.settings.plan.billingHistoryTitle': 'Billing History',
    'dashboard.settings.plan.noBillingHistory': 'No billing history',
    'dashboard.settings.plan.successCurrentPlan': 'You are already using the {name} plan.',
    'dashboard.settings.plan.successPlanChange': 'Plan change request has been received.',
    'dashboard.settings.api.description': 'Issue, manage, and delete API keys.',
    'dashboard.settings.api.newKeyTitle': 'New API Key',
    'dashboard.settings.api.newKeyLabel': 'New API Key Name',
    'dashboard.settings.api.newKeyPlaceholder': 'e.g., Production Key',
    'dashboard.settings.api.newKeyWarning': '⚠️ This key will only be displayed once. Please save it in a safe place.',
    'dashboard.settings.api.reloadButton': 'Reload',
    'dashboard.settings.api.createButton': 'Create API Key',
    'dashboard.settings.api.creatingButton': 'Creating...',
    'dashboard.settings.api.listTitle': 'API Key List',
    'dashboard.settings.api.countLabel': '{count} items',
    'dashboard.settings.api.loadingMessage': 'Loading API keys...',
    'dashboard.settings.api.noKeysMessage': 'No API keys yet. You can create one from the form above.',
    'dashboard.settings.api.activeBadge': 'Active',
    'dashboard.settings.api.createdLabel': 'Created:',
    'dashboard.settings.api.lastUsedLabel': 'Last used:',
    'dashboard.settings.api.notUsedLabel': 'Not used',
    'dashboard.settings.api.copyButton': 'Copy',
    'dashboard.settings.api.deleteButton': 'Delete',
    'dashboard.settings.api.successCreated': 'New API key created.',
    'dashboard.settings.api.successCopied': 'API key copied.',
    'dashboard.settings.api.successDeleted': 'API key deleted.',
    'dashboard.settings.api.errorLoad': 'Failed to load API keys.',
    'dashboard.settings.api.errorCreate': 'Failed to create API key.',
    'dashboard.settings.api.errorDelete': 'Failed to delete API key.',
    'dashboard.settings.api.errorLoginRequired': 'Login required.',
    'dashboard.settings.api.errorSessionNotFound': 'Authentication session not found. Please login again.',
    'dashboard.settings.dialog.deleteKey.title': 'Delete API Key',
    'dashboard.settings.dialog.deleteKey.message': 'Are you sure you want to delete the API key "{name}"? This action cannot be undone.',
    'dashboard.settings.dialog.deleteKey.confirm': 'Delete',
    'dashboard.settings.dialog.deleteKey.cancel': 'Cancel',
    'dashboard.settings.dialog.logout.title': 'Logout',
    'dashboard.settings.dialog.logout.message': 'Are you sure you want to logout?',
    'dashboard.settings.dialog.logout.confirm': 'Logout',
    'dashboard.settings.dialog.logout.cancel': 'Cancel',
    'dashboard.settings.auth.checking': 'Checking authentication status...',
    'dashboard.settings.auth.required': 'Login required',
    'dashboard.settings.auth.redirecting': 'Redirecting...',
    // API Key Modal
    'apiKeyModal.title': 'API Key Issued',
    'apiKeyModal.subtitle': 'This key will never be displayed again. Be sure to save it in a safe place.',
    'apiKeyModal.yourKey': 'Your API Key',
    'apiKeyModal.copied': 'Copied!',
    'apiKeyModal.copyButton': 'Copy API key',
    'apiKeyModal.warning.title': 'Important Notice',
    'apiKeyModal.warning.item1': 'This key will only be displayed this time',
    'apiKeyModal.warning.item2': 'Do not share with others',
    'apiKeyModal.warning.item3': 'If lost, issue a new key',
    'apiKeyModal.continue': 'Continue to Dashboard',
    'apiKeyModal.copy': 'Copy',
    // Documentation page
    'docs.page.title': 'API Documentation',
    'docs.page.subtitle': 'Financial Data API Usage and Guidelines',
    'docs.nav.tableOfContents': 'Table of Contents',
    'docs.nav.support': 'Support',
    'docs.nav.support.description': 'If you have any questions, please feel free to contact us.',
    'docs.nav.support.contact': 'Contact Support',
    'docs.section.gettingStarted': 'Getting Started',
    'docs.section.gettingStarted.introduction': 'Overview',
    'docs.section.gettingStarted.quickStart': 'Quick Start',
    'docs.section.gettingStarted.authentication': 'Authentication',
    'docs.section.apiReference': 'API Reference',
    'docs.section.apiReference.companies': 'Company Data',
    'docs.section.apiReference.financials': 'Financial Data',
    'docs.section.apiReference.analysis': 'Analysis Data',
    'docs.section.guides': 'Guides',
    'docs.section.guides.dataAnalysis': 'Data Analysis',
    'docs.section.guides.reporting': 'Report Creation',
    'docs.section.guides.automation': 'Automation',
    'docs.section.examples': 'Examples',
    'docs.section.examples.python': 'Python',
    'docs.section.examples.javascript': 'JavaScript',
    'docs.section.examples.curl': 'cURL',
    'docs.introduction.title': 'Overview',
    'docs.introduction.description1': 'The Financial Data API is a RESTful API for accessing financial information and corporate data of listed companies in Japan.',
    'docs.introduction.description2': 'Claude analyzes securities report data and provides it in a structured format.',
    'docs.introduction.features.title': 'Key Features',
    'docs.introduction.features.item1': 'Company basic information and profiles',
    'docs.introduction.features.item2': 'Financial statement data (balance sheet, income statement, cash flow statement)',
    'docs.introduction.features.item3': 'Financial analysis and insights by Claude',
    'docs.introduction.features.item4': 'Automatic summarization of securities reports',
    'docs.quickstart.title': 'Quick Start',
    'docs.quickstart.step1.title': '1. Get API Key',
    'docs.quickstart.step1.description': 'First, create an API key from your dashboard.',
    'docs.quickstart.step1.path': 'Dashboard → Account Settings → API Keys → Create New Key',
    'docs.quickstart.step2.title': '2. First Request',
    'docs.quickstart.step2.description': 'Basic example to retrieve company data:',
    'docs.quickstart.step3.title': '3. Response Format',
    'docs.quickstart.step3.description': 'The API returns JSON responses in the following format:',
    'docs.authentication.title': 'Authentication',
    'docs.authentication.description': 'All API requests must include an API key in the HTTP header in Bearer token format.',
    'docs.authentication.security.title': 'About Security',
    'docs.authentication.security.description': 'API keys are confidential information. Do not include them directly in client-side code, but manage them securely on the server-side or as environment variables.',
    'docs.apiReference.title': 'API Reference',
    'docs.apiReference.endpoint1.description': 'Get list of companies',
    'docs.apiReference.endpoint1.param1.name': 'industry',
    'docs.apiReference.endpoint1.param1.description': 'Filter by industry (optional)',
    'docs.apiReference.endpoint1.param2.name': 'market',
    'docs.apiReference.endpoint1.param2.description': 'Filter by market (optional)',
    'docs.apiReference.endpoint1.param3.name': 'limit',
    'docs.apiReference.endpoint1.param3.description': 'Number of items to retrieve (default: 20)',
    'docs.apiReference.endpoint2.description': 'Get details of a specific company',
    'docs.apiReference.endpoint2.param1.name': 'id',
    'docs.apiReference.endpoint2.param1.description': 'Company ID (required)',
    'docs.apiReference.endpoint3.description': 'Get company financial data',
    'docs.apiReference.endpoint3.param1.name': 'id',
    'docs.apiReference.endpoint3.param1.description': 'Company ID (required)',
    'docs.apiReference.endpoint3.param2.name': 'year',
    'docs.apiReference.endpoint3.param2.description': 'Target year (optional)',
    'docs.apiReference.endpoint3.param3.name': 'quarter',
    'docs.apiReference.endpoint3.param3.description': 'Quarter (1-4, optional)',
    'docs.apiReference.parameters': 'Parameters',
    'docs.apiReference.parameterTable.name': 'Name',
    'docs.apiReference.parameterTable.type': 'Type',
    'docs.apiReference.parameterTable.description': 'Description',
    'docs.examples.title': 'Examples',
    'docs.dataAnalysis.title': 'Data Analysis Guide',
    'docs.dataAnalysis.claude.title': 'Analysis by Claude',
    'docs.dataAnalysis.claude.description': 'Automatically analyze securities reports and provide important insights',
    'docs.dataAnalysis.feature1.title': 'Financial Analysis',
    'docs.dataAnalysis.feature1.description': 'Automatic calculation of profitability, growth, and safety indicators',
    'docs.dataAnalysis.feature2.title': 'Risk Assessment',
    'docs.dataAnalysis.feature2.description': 'Identify and evaluate potential corporate risks',
    'docs.dataAnalysis.feature3.title': 'Industry Comparison',
    'docs.dataAnalysis.feature3.description': 'Detailed comparative analysis with competitors',
    'docs.dataAnalysis.feature4.title': 'Predictive Models',
    'docs.dataAnalysis.feature4.description': 'Future performance forecasts and scenario analysis',
    'docs.dataAnalysis.usage.title': 'How to Use Analysis Data',
    'docs.dataAnalysis.usage1.title': 'Investment Decisions',
    'docs.dataAnalysis.usage1.description': 'Develop investment strategies based on financial indicators and analysis results',
    'docs.dataAnalysis.usage2.title': 'Report Creation',
    'docs.dataAnalysis.usage2.description': 'Detailed financial analysis reports for clients',
    'docs.dataAnalysis.usage3.title': 'Risk Monitoring',
    'docs.dataAnalysis.usage3.description': 'Regular financial health checks and alert settings',
    'docs.faq.title': 'Frequently Asked Questions',
    'docs.faq.q1': 'Are there any API usage limits?',
    'docs.faq.a1': 'Monthly request limits depend on your plan. The Standard plan allows up to 10,000 requests per month.',
    'docs.faq.q2': 'How often is data updated?',
    'docs.faq.a2': 'Data is typically updated within 24 hours after securities report submission. Quarterly reports are updated within 48 hours after submission.',
    'docs.faq.q3': 'Which companies\' data is available?',
    'docs.faq.a3': 'We provide data for all companies listed on the Tokyo Stock Exchange Prime, Standard, and Growth markets.',
    'docs.faq.q4': 'What should I do if my API key is compromised?',
    'docs.faq.a4': 'Immediately delete the compromised API key from your dashboard and create a new API key.',
    // SearchDemo component
    'home.searchDemo.badge': 'Interactive API',
    'home.searchDemo.title': 'Real-Time',
    'home.searchDemo.titleSuffix': 'Financial Analysis',
    'home.searchDemo.subtitle': 'Instantly access financial data. Analysis powered by Claude MCP.',
    'home.searchDemo.videoHeader': 'XBRL Financial API Demo',
    'home.searchDemo.interactiveMode': 'Interactive Mode',
    'home.searchDemo.videoMode': 'Video Mode',
    'home.searchDemo.demoVideoTitle': 'Demo Video',
    'home.searchDemo.demoVideoDescription': 'See XBRL Financial API in action. Watch how we instantly retrieve corporate financial data and provide insights through AI analysis.',
    'home.searchDemo.realtimeData': 'Real-Time Data',
    'home.searchDemo.realtimeDataDesc': 'Get latest financial information instantly',
    'home.searchDemo.aiAnalysis': 'AI Analysis',
    'home.searchDemo.aiAnalysisDesc': 'Advanced analysis by Claude',
    'home.searchDemo.easyApi': 'Easy-to-Use API',
    'home.searchDemo.easyApiDesc': 'Simple RESTful design',
    'home.searchDemo.inputPlaceholder': 'Company name or code',
    'home.searchDemo.analyzing': 'Analyzing...',
    'home.searchDemo.execute': 'Execute',
    'home.searchDemo.error': 'Error:',
    'home.searchDemo.responseTime': 'Response time: {time}ms',
    'home.searchDemo.jsonResponse': 'JSON Response',
    'home.searchDemo.analysisResult': 'Analysis Result',
    'home.searchDemo.analysisText': 'Retrieved financial data for {company}. ROE {roe}%, market cap {marketCap} - an excellent company. ESG score of {esg} indicates sustainable management.',
    'home.searchDemo.startMessage': 'Enter company name or code to start analysis',
    'home.searchDemo.feature1.title': 'AI Analysis',
    'home.searchDemo.feature1.desc': 'Intuitive interface in Claude Desktop style',
    'home.searchDemo.feature2.title': 'Rich Data',
    'home.searchDemo.feature2.desc': 'Access to 5 years of securities report data',
    'home.searchDemo.feature3.title': 'Analysis by Claude',
    'home.searchDemo.feature3.desc': 'Easy data retrieval.',
    // IndependentFeatureCards component
    'home.features.badge': 'Premium Features',
    'home.features.title': 'Professional Financial Analysis',
    'home.features.titleSuffix': 'to Shape Your Investment Future',
    'home.features.subtitle1': 'With high-accuracy financial data and user-friendly interface,',
    'home.features.subtitle2': 'streamline your investment analysis.',
    'home.features.feature1.title': 'Real-Time Financial Analysis',
    'home.features.feature1.description': 'Deeply understand corporate financial conditions with detailed financial indicators and data analysis',
    'home.features.feature1.highlight1': 'Real-time retrieval of latest financial data',
    'home.features.feature1.highlight2': 'AI-generated automatic analysis reports',
    'home.features.feature1.highlight3': 'Multi-company comparison analysis',
    'home.features.feature2.title': 'Securities Report Summary',
    'home.features.feature2.description': 'Claude automatically extracts and summarizes important information from securities reports',
    'home.features.feature2.highlight1': 'Automatic extraction of key items',
    'home.features.feature2.highlight2': 'Executive summary creation',
    'home.features.feature2.highlight3': 'Risk factor visualization',
    'home.features.feature3.title': 'Securities Report Data Processing',
    'home.features.feature3.description': 'Automated data processing by Claude converts complex securities report data into user-friendly formats',
    'home.features.feature3.highlight1': 'Automatic conversion to structured data',
    'home.features.feature3.highlight2': 'Excel and CSV export',
    'home.features.feature3.highlight3': 'Customizable output formats',
    'home.features.watchDemo': 'Watch Demo',
    'home.features.backToImage': 'Back to Image',
    'home.features.viewDetails': 'View Details',
    'home.features.cta.title': 'Experience Professional Features',
    'home.features.cta.description': 'Try the Standard plan today.',
    'home.features.cta.button': 'Try Standard',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('ja');

  // Load language from localStorage on mount
  useEffect(() => {
    const saved = localStorage.getItem('language') as Language;
    if (saved && (saved === 'ja' || saved === 'en')) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['ja']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}