name: Build Status Notifications

on:
  workflow_run:
    workflows: ["Node.js CI", "Vercel Production Deployment"]
    types:
      - completed

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    if: ${{ secrets.SLACK_WEBHOOK != '' }}
    steps:
      - name: Send Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ github.event.workflow_run.conclusion }}
          text: |
            Workflow: ${{ github.event.workflow_run.name }}
            Status: ${{ github.event.workflow_run.conclusion }}
            Branch: ${{ github.event.workflow_run.head_branch }}
            Commit: ${{ github.event.workflow_run.head_commit.message }}
            Author: ${{ github.event.workflow_run.head_commit.author.name }}
            Run URL: ${{ github.event.workflow_run.html_url }}
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          channel: '#ci-cd'
          username: 'GitHub Actions'
          icon_emoji: ':github:'
          color: ${{ github.event.workflow_run.conclusion == 'success' && 'good' || 'danger' }}

  notify-discord:
    runs-on: ubuntu-latest
    if: ${{ secrets.DISCORD_WEBHOOK != '' }}
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          CONCLUSION="${{ github.event.workflow_run.conclusion }}"
          COLOR=$([ "$CONCLUSION" == "success" ] && echo "3066993" || echo "15158332")

          curl -X POST $DISCORD_WEBHOOK \
            -H "Content-Type: application/json" \
            -d '{
              "username": "GitHub Actions",
              "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
              "embeds": [{
                "title": "'"${{ github.event.workflow_run.name }}"'",
                "description": "Build '"$CONCLUSION"' on branch '"${{ github.event.workflow_run.head_branch }}"'",
                "color": '"$COLOR"',
                "fields": [
                  {
                    "name": "Commit",
                    "value": "'"${{ github.event.workflow_run.head_commit.message }}"'",
                    "inline": false
                  },
                  {
                    "name": "Author",
                    "value": "'"${{ github.event.workflow_run.head_commit.author.name }}"'",
                    "inline": true
                  },
                  {
                    "name": "Status",
                    "value": "'"$CONCLUSION"'",
                    "inline": true
                  }
                ],
                "url": "'"${{ github.event.workflow_run.html_url }}"'",
                "timestamp": "'"$(date -u +%Y-%m-%dT%H:%M:%S.000Z)"'"
              }]
            }'